apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vibecheck.labels" . | nindent 4 }}
    app.kubernetes.io/name: kafka
spec:
  type: ClusterIP
  ports:
    - name: kafka
      port: {{ .Values.infrastructure.kafka.port }}
      targetPort: kafka
  selector:
    app.kubernetes.io/name: kafka
