apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vibecheck.labels" . | nindent 4 }}
    app.kubernetes.io/name: mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: {{ .Values.infrastructure.mysql.port }}
      targetPort: mysql
  selector:
    app.kubernetes.io/name: mysql
