apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "vibecheck.labels" . | nindent 4 }}
    app.kubernetes.io/name: redis
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: {{ .Values.infrastructure.redis.port }}
      targetPort: redis
  selector:
    app.kubernetes.io/name: redis
